#!/usr/bin/env sh

set -eux

SCRIPT=$(readlink -f "$0")
export BASE_DIRECTORY=$(dirname "$SCRIPT")


readonly BASE_KS_DIR="${BASE_DIRECTORY}/live"
readonly BASE_KS='polyprog-thin-client.ks'
readonly NAME='PolyProg-ThinClient'

readonly FLAT_KS="flat-${BASE_KS}"

rm -rf ${BASE_DIRECTORY}/logs
rm -rf ${BASE_DIRECTORY}/results/

if ! [ -f ${BASE_DIRECTORY}/skel/.setup.env ]; then
    echo "WARNING: File ${BASE_DIRECTORY}/skel/.setup.env does not exist, you won't have WiFi!"
fi

# TODO : source the file above and check that all required environment variables are set


ksflatten --config "${BASE_KS_DIR}/${BASE_KS}" --output "${FLAT_KS}" \

livemedia-creator --ks "${FLAT_KS}" \
		  --project "${NAME}" --volid "${NAME}" \
		  --iso-name "${NAME}.iso" --title "${NAME}" \
		  --make-iso --iso-only --macboot \
		  --lorax-templates "${BASE_DIRECTORY}/lorax-templates" \
		  --resultdir ${BASE_DIRECTORY}/results/ \
		  --logfile ${BASE_DIRECTORY}/logs/main.log \
		  --dracut-arg="--add dmsquash-live" \
		  --dracut-arg="--omit convertfs plymouth livenet qemu qemu-net pollcdrom" \
		  --dracut-arg="--debug" \
		  --dracut-arg="--no-early-microcode" \
 		  --no-virt
